### ISSUE TITLE
Please add some funtion

### ISSUE THREAD

**Issue by benthebear** [palasthotel/ph-wp-content-relations#1]
I would be soooo happy if we got a few function for usage in other plugins or themes:

content_realtion_add_realtion($post_id_first, $post_id_second, $relation_type);

content_realtion_get_realtion_by_post_id($post_id);

content_realtion_get_realtion_by_post_id_and_type($post_id_first, $relation_type);

**Comment by EdwardBock** [comment]
Already done!
