### ISSUE TITLE
Sortable

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/ph-wp-content-relations#2]
Make the list sortable with drag and drop

**Comment by EdwardBock** [comment]
Done!

**Comment by juliakleinediekmann** [comment]
Hi @EdwardBock,

I have a request from a client: He would like to have an indicator that says "you can sort this items  by drag and drop", so everyone knows this feature immediatly.

**Comment by StefanBoettcherASMB** [comment]
Hi @EdwardBock, I would suggest visually marked and separated drag & drop handles to make it
a) more obvious and
b) don't make the whole element the drag & drop handler. some users want to copy text from inside the element and right now they lost that ability

**Comment by EdwardBock** [comment]
Sortable handler icon was added in version 1.0.4

**Comment by StefanBoettcherASMB** [comment]
yay!
